---
- name: Update /etc/apt/sources.list
  get_url: 
    url: REPOSITORY_URL_HERE
    dest: /etc/apt/sources.list
    force: yes
  become: yes

- name: Refresh apt cache
  apt:
    update_cache: yes
  become: yes
