---
- name: Retrieve Netbox VRF ID
  environment:
    no_proxy: netbox.5thc.co
  uri:
    url: http://netbox.5thc.co/api/ipam/vrfs/?tenant={{ openstack.location.project.name }}
    method: GET
    headers:
      Authorization: "Token {{ netbox_api_token }}"
      Accept: 'application/json'
  register: res

- name: POST to Netbox
  uri:
    url: http://netbox.5thc.co/api/ipam/ip-addresses/
    method: POST
    headers:
      Authorization: "Token {{ netbox_api_token }}"
      Content-Type: 'application/json'
      Accept: 'application/json'
    return_content: yes
    body_format: json
    body: '{"vrf": "{{ res.json.results[0].id }}","tenant":"{{ openstack.location.project.name }}","address":"{{ ansible_ssh_host | ipaddr }}","description":"{{ ansible_nodename }}"}' 
