---
- name: Retrieve Netbox VRF ID
  uri:
    url: http://netbox.5thc.co/api/ipam/vrfs/?tenant={{ openstack.location.project.name }}
    method: GET
    headers:
      Authorization: "Token {{ netbox_api_token }}"
      Accept: 'application/json'
  register: res

- name: Debug response
  debug:
    msg: "{{ res.json.results.id }}"

- name: POST to Netbox
  uri:
    url: http://netbox.5thc.co/api/ipam/ip-addresses/
    method: POST
    body: "{{ lookup('template', 'ip-addr-post.j2') }}"
    headers:
      Authorization: "Token {{ netbox_api_token }}"
      Content-Type: 'application/json'
      Accept: 'application/json'
    return_content: yes
    body_format: json
