---
# vars file for zabbix-agent (Debian)

zabbix_agent: zabbix-agent
zabbix_agent_service: zabbix-agent
zabbix_agent_conf: zabbix_agentd.conf

zabbix_version: 4.0
zabbix_repo: zabbix
zabbix_agent_package: zabbix-agent
zabbix_sender_package: zabbix-sender
zabbix_get_package: zabbix-get
zabbix_agent_package_state: present
zabbix_agent_server: 10.128.233.190
zabbix_agent_serveractive: 10.128.233.190
zabbix_selinux: False

# Zabbix API stuff
zabbix_url: "http://10.128.233.190/zabbix"
zabbix_api_user: Admin
zabbix_api_pass: zabbix
zabbix_api_create_hostgroup: False
zabbix_api_create_hosts: False
zabbix_create_hostgroup: present  # or absent
zabbix_create_host: present       # or absent
zabbix_update_host: yes
zabbix_host_status: enabled       # or disabled
zabbix_proxy: null
zabbix_inventory_mode: disabled
zabbix_useuip: 1
zabbix_host_groups:
  - Linux servers
zabbix_link_templates:
  - Template OS Linux

zabbix_agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ zabbix_agent_ip }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ zabbix_agent_listenport }}"

zabbix_agent_firewall_enable: False
zabbix_agent_firewalld_enable: False
zabbix_agent_firewalld_source: "{{ zabbix_agent_server }}"
# Zabbix configuration variables
zabbix_agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
zabbix_agent_logfile: /var/log/zabbix/zabbix_agentd.log
zabbix_agent_logfilesize: 100
zabbix_agent_debuglevel: 3
zabbix_agent_sourceip:
zabbix_agent_enableremotecommands: 0
zabbix_agent_logremotecommands: 0
zabbix_agent_listenport: 10050
zabbix_agent_listeninterface:
zabbix_agent_listenip:
zabbix_agent_startagents: 3
zabbix_agent_hostname: "{{ inventory_hostname }}"
zabbix_agent_hostnameitem:
zabbix_agent_hostmetadata:
zabbix_agent_hostmetadataitem:
zabbix_agent_refreshactivechecks: 120
zabbix_agent_buffersend: 5
zabbix_agent_buffersize: 100
zabbix_agent_maxlinespersecond: 100
zabbix_agent_allowroot: 0
zabbix_agent_zabbix_alias:
zabbix_agent_timeout: 3
zabbix_agent_include: /etc/zabbix/zabbix_agentd.d
zabbix_agent_unsafeuserparameters: 0
zabbix_agent_userparameter:
zabbix_agent_userparameters: []
zabbix_agent_custom_scripts: false
zabbix_agent_loadmodulepath: ${libdir}/modules
zabbix_agent_loadmodule:

# TLS settings
zabbix_agent_tlsconnect:
zabbix_agent_tlsaccept:
zabbix_agent_tlscafile:
zabbix_agent_tlscrlfile:
zabbix_agent_tlsservercertissuer:
zabbix_agent_tlsservercertsubject:
zabbix_agent_tlscertfile:
zabbix_agent_tlskeyfile:
zabbix_agent_tlspskidentity:

zabbix_agent_tls_config:
  unencrypted: '1'
  psk: '2'
  cert: '4'

sign_keys:
  "40":
    bionic:
      sign_key: A14FE591
    sonya:
      sign_key: A14FE591
    serena:
      sign_key: A14FE591
    stretch:
      sign_key: A14FE591
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    xenial:
      sign_key: E709712C
  "34":
    bionic:
      sign_key: A14FE591
    sonya:
      sign_key: A14FE591
    serena:
      sign_key: A14FE591
    stretch:
      sign_key: A14FE591
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    xenial:
      sign_key: E709712C
  "32":
    sonya:
      sign_key: 79EA5ED4
    serena:
      sign_key: 79EA5ED4
    stretch:
      sign_key: A14FE591
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    xenial:
      sign_key: E709712C
  "30":
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    stretch:
      sign_key: A14FE591
    trusty:
      sign_key: 79EA5ED4
    xenial:
      sign_key: E709712C
  "24":
    wheezy:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    precise:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
  "22":
    squeeze:
      sign_key: 79EA5ED4
    jessie:
      sign_key: 79EA5ED4
    precise:
      sign_key: 79EA5ED4
    trusty:
      sign_key: 79EA5ED4
    lucid:
      sign_key: 79EA5ED4

suse:
  "openSUSE Leap":
    "42":
      name: server:monitoring
      url: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_Leap_{{ ansible_distribution_version }}/
  "openSUSE":
    "12":
      name: server_monitoring
      url: http://download.opensuse.org/repositories/server:/monitoring/openSUSE_{{ ansible_distribution_version }}
  "SLES":
    "11":
      name: server_monitoring

